### PR TITLE
update dependency and add generation make file

### PR DESCRIPTION
**Pull request by sbezverk**
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>

### CODE REVIEW

**Comment by sbezverk** [comment]
@sbyx  please take a look

**Comment by serenibyss** [comment]
Any updates on this? Would love to see this PR be merged

**Comment by srebhan** [comment]
Are there any considerations to merge this at some point?

**Comment by sbezverk** [comment]
@srebhan  man it has been PR for so long, I am afraid it is outdated, with new go gRPC bits and 1.18, probably another refresh would be good, IF the repo owner agrees to merge it anytime soon.

**Comment by sbyx** [comment]
Sorry got lost in my mailbox.

**Pull request merged**
