### PR TITLE
Add delete field

### PR DESCRIPTION
**Pull request by severindellsperger**
This PR adds the delete field (which is only set for a delete event). Please review the changes and merge them if everything looks good to you.

### CODE REVIEW

**Comment by sbezverk** [comment]
@severindellsperger  could you please add a little background where `delete` is coming from, it is a bit odd to see `delete` in a telemetry message. who is the producer of such message, supported platforms and if possible versions. Thank you.

**Comment by sbezverk** [comment]
looks good to me, I checked the latest XR code and delete is there, so it is good to have the proto in sync.

**Comment by severindellsperger** [comment]
> @severindellsperger could you please add a little background where `delete` is coming from, it is a bit odd to see `delete` in a telemetry message. who is the producer of such message, supported platforms and if possible versions. Thank you.

The `delete` is, obviously, only sent if telemetry model-driven is configured event-based. If so and the router detects a delete event, the delete key will be set in the telemetry message. Otherwise, the delete tag is not there. A good overview is provided by the following resources:
- https://www.cisco.com/c/en/us/support/docs/routers/asr-9000-series-aggregation-services-routers/215321-asr9k-model-driven-telemetry-whitepaper.html#anc12
- https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-1/telemetry/configuration/guide/b-telemetry-cg-asr9000-71x/b-telemetry-cg-asr9000-71x_chapter_01.html#id_117821
- https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/progammability/guide/b-cisco-nexus-9000-series-nx-os-programmability-guide-93x/b-cisco-nexus-9000-series-nx-os-programmability-guide-93x_chapter_0101001.html

So, the supported platforms are for sure NXOS, and IOS-XR. I think IOS-XE supports EDT too, but I'm not sure how they handle it. In IOS-XR it was introduced in 6.5.1, see here: https://github.com/ios-xr/model-driven-telemetry/blob/master/protos/65x/telemetry.proto
When exactly the feature was introduced in NXOS I can't find it online.

I hope this helps.

**Comment by severindellsperger** [comment]
> looks good to me, I checked the latest XR code and delete is there, so it is good to have the proto in sync.

Yes, it is there. I have updated the proto file based on the `telemetry.proto` file from the IOS-XR proto repo. See latest available file: https://github.com/ios-xr/model-driven-telemetry/blob/master/protos/772/telemetry.proto

**Comment by sbyx** [comment]
Thanks!

**Pull request merged**
